apiVersion: batch/v1
kind: Job
metadata:
  name: data2-train-job
  labels: {site: data2, type: train}
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
      - name: yolo-container
        image: yolov8-project:latest
        imagePullPolicy: IfNotPresent
        command: [python3, train_yolo.py, --site, data2_processed, --epochs, '2',
          --imgsz, '640']
        env:
        - {name: PYTHONUNBUFFERED, value: '1'}
        volumeMounts:
        - {name: app-volume, mountPath: /app}
      restartPolicy: Never
      volumes:
      - name: app-volume
        hostPath: {path: /mnt/host/e/Ancious/Desktop/毕业设计/Code, type: Directory}
  backoffLimit: 4
